
== Betriebshandbuch

In diesem Teil der Dokumentation befinden sich Informationen zu
den Systemvoraussetzungen und der Installation für den Betrieb
des XPlanPortal. Die Webanwendungen basieren auf den Komponenten des
Open-Source-Projekts http://www.geomajas.org/[Geomajas].

[Systemüberblick]
=== Systemüberblick

Als zugrunde liegende Basistechnologien des XPlanPortals werden Java und Apache Tomcat verwendet.
Zur erfolgreichen Installation müssen die in diesem Kapitel beschriebenen Voraussetzungen erfüllt werden.


[[betriebssystem]]
==== Betriebssystem

Als Betriebssystem kann ein beliebiges 64-bit Betriebssystem verwendet
werden, das Java SE 7 (http://www.oracle.com/technetwork/java/javase/downloads/index.html[Oracle
JRE 1.7]) unterstützt.

NOTE: Empfohlen wird die Nutzung eines der folgenden Betriebssysteme: Debian
Wheezy, SLES 11 SP4, Oracle Linux 7, CentOS 7.x, Windows Server 2008
R2/2012 R2.

NOTE: Das Gebietsschema des Betriebssystems ("Locale") sollte auf deutsch
konfiguriert sein, da einzelne Fehlerbeschreibungen in dieser Sprache
ausgegeben werden. Unter Linux kann das
Gebietsschema beispielsweise in der Datei "/etc/default/locale"
angepasst werden.

NOTE: Empfohlen wird Oracle JDK 1.7_45+.


[[java-applikationsserver]]
==== Java Applikationsserver

Als Applikationsserver wird Apache Tomcat in der Version 7 empfohlen.
Das Installationsarchiv findet sich bei der
http://tomcat.apache.org[Apache Foundation]. Diese Dokumentation bezieht
sich grundsätzlich auf den Apache Tomcat.

NOTE: Die minimale Anforderung an den Applikationsserver ist das Java EE 6 Web
Profil. Empfohlen wird Apache Tomcat Version 7.0.32+.

[[systemvoraussetzungen]]
==== Systemvoraussetzungen


[[server]]
===== Server


[[minimale-systemvoraussetzung]]
====== Minimale Systemvoraussetzung

________________________________________________________________________________________________________________________
* CPU: 2 CPUs mit je 2 Kernen (2x DualCore) oder 1 CPU mit 4 Kernen (1x
QuadCore) - minimal 2,0-GHz-Prozessor mit 64 Bit
* Arbeitsspeicher: 8 GB RAM
* Netzwerkadapter: Gigabit-Ethernet-Adapter (10/100/1000baseT PHY/MAC)
* Festplattensystem: Journaling-Dateisystem (Kapazität nach Bedarf,
Minimum 500 GB)
________________________________________________________________________________________________________________________

[[empfohlene-systemkonfiguration]]
====== Empfohlene Systemkonfiguration

______________________________________________________________________________________________________________
* CPU: 2 CPUs mit je 4 Kernen (2x QuadCore) or 1 CPU mit 8 Kernen (1x
OctaCore) - 3,0-GHz-Prozessor mit 64 Bit
* Arbeitsspeicher: 32 GB RAM
* Netzwerkadapter: Gigabit-Ethernet-Adapter (10/100/1000baseT PHY/MAC)
* Festplattensystem: RAID-10 (Kapazität nach Bedarf, Minimum 500 GB)
optional mit SSD
______________________________________________________________________________________________________________

[[client]]
===== Client

_____________________________________________
* CPU: 1 CPU mit mindestens 1,4-GHz-Prozessor
* Arbeitsspeicher: 4 GB RAM
_____________________________________________

NOTE: Weitere Informationen zu den Systemvoraussetzungen bei den unterstützten
Browsern: Microsoft Internet Explorer (9, 10, 11), Mozilla Firefox: 36+,
Google Chrome: 40+

=== Installation

[[Installation_Konfigurationsdateien]]
==== Konfigurationsdateien

Die die Konfiguration enthaltenen __jar__-Archive müssen in das Verzeichnis _.deegree/portal-configuration_ im Home-Verzeichnis des Nutzers kopiert (aber nicht entpackt) werden:
______________________
* _xplan-bplan-config_
* _xplan-fplan-config_
* _xplan-lplan-config_
______________________

==== Anwendungen

Die WAR-Archive der XPlanPortal-Komponenten werden über eine Tomcat-Installation bereitgestellt:

______________________
* _portal-bplan.war_
* _portal-fplan.war_
* _portal-lplan.war_
______________________

==== Konfiguration des Applikationsservers

Im Applikationsserver muss die Konfiguration des XPlanPortals dem Tomcat bekannt gegeben
werden. Dazu muss der Classpath um die Referenzen auf die Konfigurations-JARs der Portale erweitert werden. Wurde die Anleitung in Abschnitt <<Installation_Konfigurationsdateien>> befolgt, befinden sich die drei jar-Dateien im Verzeichnis _.deegree_ im Home-Verzeichnis des
Nutzers.


[[linux]]
===== Linux

Für die Konfiguration der oben genannten Punkte muss zunächst im
Verzeichnis _<tomcat-root>/bin_ eine neue Datei mit dem Namen
_setenv.sh_ angelegt werden.

Für die Konfiguration der XPlanPortale werden die Verweise auf die
Konfigurations-JARs der Portale eingetragen, getrennt mit einem
Doppelpunkt (__:__):

+
CLASSPATH=<root>/.deegree/xplan-bplan-config-1.0.jar:<root>/.deegree/xplan-fplan-config-1.0.jar:<root>/.deegree/xplan-lplan-config-1.0.jar
+

NOTE: Es müssen ggf. Zeilenumbrüche entfernt werden.


[[windows]]
===== Windows

Für die Konfiguration der *XPlanPortale* wird im Verzeichnis
_<tomcat-root>/conf_ die Datei mit dem Namen _catalina.properties_
angepasst. Der Verweis auf die Konfigurations-JARs der XPlanPortale muss
unter _common.loader_ eingetragen werden, getrennt mit einem Komma
(__,__). Die Tomcat eigenen JAR Dateien, müssen unbedingt beibehalten
werden. :

+
common.loader=C:\.deegree\xplan-bplan-config-1.0.jar;,C:\.deegree\xplan-fplan-config-1.0.jar;,C:\.deegree\xplan-lplan-config-1.0.jar;,$\{catalina.base}\lib,$\{catalina.base}\lib\__.jar,$\{catalina.home}\lib,$\{catalina.home}\lib\__.jar
+


[Anwendung starten]
=== Anwendung starten

Zum Start des XPlanPortal muss das Start-Skript der
Tomcat-Installationen ausgeführt werden:

----
~/tomcat7/bin/catalina.sh [start | stop]
----

[Migration der Anwendung (Beispiele)]
=== Migration der Anwendung (Beispiele)

Bei einem Hostumzug, bei dem sich der Hostname des Servers ändert, muss
die URL in mehreren Konfigurationen angepasst werden, damit die
Funktionalität der Anwendungen gewährleistet ist. Dabei müssen folgende
Anpassungen erfolgen:

[[fuer-die-planungs-portale]]
==== Für die Planungs-Portale:

____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
* _layer[B|F|L]Plan.xml_, _layer[B|F|L]PlanWFS.xml_, _layer[B|F|L]PRaster.xml_ und _featureHitsRetriever[B|F|L]P.xml_ (in der
jeweiligen jar-Datei der XPlanPortal-Webkomponenten
_.deegree/portal-configuration/<portal>-config.jar_)
* _dropDownList.xml_ (im Ordner der jeweiligen XPlanPortal-Webkomponente
_<tomcat>/webapps/<portal-portalname>_)
____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

*Anpassung in den Dateien layer[B|F|L]Plan.xml, layer[B|F|L]PlanWFS.xml,
layer[B|F|L]PRaster.xml und featureHitsRetriever[B|F|L]P.xml:*

Für die Planungs-Portale müssen in den genannten Dateien alle Werte der
Properties _baseWmsUrl_ (layer[B|F|L]Plan.xml und
layer[B|F|L]PRaster.xml) bzw. _values_ (layer[B|F|L]PlanWFS.xml) und
_wfsRequestUrlForBboxFeatureHits_ (featureHitsRetriever[B|F|L]P.xml),
die einen der deegree Dienste referenzieren, angepasst werden.

Beispiel _layerBPlan.xml_:

----
...
<bean name="bp_plan" class="de.latlon.xplanung.layer.wms.XPlanWmsLayer">
    <property name="layerInfo" ref="layer_bp_plan_ref" />
    <property name="baseWmsUrl" value="http://<host>:<port>/<service>/service/wms?" />
    <property name="version" value="1.1.1" />
...
----

Für mehr Details sowie Hinweise zur Bearbeitung von jar-Dateien siehe
Kapitel <<XPlanPortal>>

*Anpassungen in der Datei dropDownList.xml:*

Damit ein Wechsel zwischen den Planungs-Portalen über die Dropdown Liste
möglich ist, muss die <link>-Referenz der jeweiligen Portale angepasst
werden.

----
<List>
  <entry>
    <label>Bebauungspläne</label>
    <link>http://<host>:<port>/portal-<portalname>/</link>
  </entry>
  ...
</List>
----

Für mehr Details siehe Kapitel <<XPlanPortal>>

include::configuration_portal.adoc[]